### PR TITLE
Fix for the nested attributes issue I ran into

### PR DESCRIPTION
**Pull request by kb1ibt**
See Issue #3 for what I ran into.

### CODE REVIEW

**Comment by albertopq** [comment]
Sorry mate,

I've not approved this pull request because I'm refactoring the whole plugin contemplating the issue that you submitted. I'm adding some tests as well.

I'll let you know when is up (hopefully tomorrow)

Thanks for your contribution!

**Comment by triemstr** [comment]
+1

**Comment by albertopq** [comment]
I've just uploaded the new version. Check it out and let me know if you have some issues.

Cheers.

**Comment by triemstr** [comment]
This seems to work for me, and hopefully it is working for kb1ibt, too.

**Comment by kb1ibt** [comment]
version 0.2.0 fixed this issue

**Pull request closed without merging**
